BaseAdresseNationale/mes-adresses

components/map/hooks/layers.js
components/map/hooks/sources.js
components/map/layers/numeros.js
components/map/map.js
components/map/numero-marker.js

- Les points garde leur code couleur qu'ils soient sélectionné ou non
- Le curseur de la souris change si un point est cliquable
- Les numéros sont affichés par défaut quand une voie est sélectionnée
- Ajout d'un niveau de zoom maximum
- Ajoute la possibilité de changer de voie depuis la carte même si une autre est déjà choisie
- Si une voie est survolée, tous ses points apparaissent en surbrillance

Améliore l'expérience utilisateur de la carte

---

pages/all.js
pages/index.js
pages/new/index.js

Lorsqu'une BAL n'a qu'une seule commune, celle-ci est automatiquement sélectionnée.

Sélection automatique des communes seules

---

components/map/map.js
components/map/numero-marker.js
hooks/error.js

Un clique droit sur un numéro ou un toponyme ouvre un menu contextuel permettant de supprimer l'adresse.

Supprimer une adresse depuis la carte

---

components/map/hooks/layers.js
components/map/hooks/sources.js
components/map/layers/numeros.js
components/map/layers/voies.js
components/map/map.js

Nouveautés:
- Coloration du label d'une voie pendant le survole
- Affichage des numéros en dehors de la voie sélectionnée
- Affichage adapté des `layers` en fonction du zoom

Amélioration de la navigation entre les voies depuis la carte

---

components/bases-locales-list.js
components/header.js
components/user-bases-locales.js
lib/tokens.js
pages/all.js
pages/index.js
pages/new/create-form.js
pages/new/index.js
pages/new/upload-form.js
pages/new/upload.js

La page d’accueil affiche désormais la liste des bases adresses locales auxquelles l'utilisateur a accès et un bouton permettant d'accéder au formulaire de création d'une base adresse locale.
Le formulaire de création a lui aussi évolué. Il affiche maintenant deux onglets permettant de passer de la création d'une base adresse locale depuis la BAN à l'import d'un fichier CSV.
- Un nouveau bouton "Accueil" fait son apparition

Nouvelle page d'accueil 

---

pages/new/upload-form.js

Cette PR apporte deux corrections importantes:
1. Jusqu'à maintenant une nouvelle BAL était crée à chaque fois que le bouton "Créer la Base Adresse Locale" était cliqué.
2. Une nouvelle BAL est crée même si le fichier `csv` n'est pas valide.
Ces deux problèmes sont résolus. Une seul BAL est crée et il n'est plus possible de valider le formulaire si le fichier passer est invalide.

Correction de la création d'un BAL via l'import CSV

---

components/header.js
components/map/numero-marker.js
package.json

Indiquer si l'utilisateur a les droits d'édition sur la BAL

---

pages/_app.js

En vu des nombreux défauts d'expérience utilisateur que rencontrer sur la version mobile, il est préférable d'afficher un avertissement en attendant une version mobile plus soignée.

Avertissement pour les utilisateurs mobile

---

components/delete-warning.js
pages/bal/commune.js
pages/bal/index.js

Message d'avertissement de suppression

---

components/table-row.js
pages/bal/commune.js
pages/bal/index.js
pages/bal/voie.js

- Lorsqu'ils sont survolés, un icon ✏️ s'affiche à côté de la voie ou du numéro si ceux-ci sont éditables.
- Des nouvelles informations s'affiche au dessus de la liste afin d'apporter plus de détails au contexte courant. On y retrouve le nom de la BAL, de la commune ou de la voie mais aussi le nombre de communes d'une BAL, de voies d'une commune et le nombre de numéros d'une voie.
- Il est possible d'éditer le nom d'une voie directement depuis ce contexte

Améliorations de l’expérience utilisateur

---

.env.sample
components/bases-locales-list.js
components/user-bases-locales.js
helpers/bases-locales.js
lib/adresse-backend/index.js
lib/bal-api/index.js
lib/tokens.js
next.config.js
pages/all.js

Ajoute un badge ![Capture d’écran 2019-06-12 à 16 31 43](https://user-images.githubusercontent.com/7040549/59360300-275f1480-8d30-11e9-9de2-63ea0727ddaf.png) si une base adresse locale est publiée ou ![Capture d’écran 2019-06-12 à 16 31 22](https://user-images.githubusercontent.com/7040549/59360302-27f7ab00-8d30-11e9-91dd-f1063fb3f184.png)
si elle est en cours d'édition.
Le bouton <img width="35" alt="Capture d’écran 2019-06-14 à 14 40 57" src="https://user-images.githubusercontent.com/7040549/59509871-88aef100-8eb2-11e9-9dbb-957f2320b903.png"> permet de supprimer une Base Adresse Locale.
------------

Affiche l'état de publication des BAL et permet leur suppression

---

components/bases-locales-list.js
components/header.js
helpers/bases-locales.js
lib/adresse-backend/index.js
lib/bal-api/index.js
lib/geo-api/index.js

- Ajoute des valeurs par défaut aux variables d'environnement
- Fait disparaitre le button "supprimer" de la liste `/all`

Corrige l'affichage des BAL publiée

---

components/header/index.js

Fix #95 Publication impossible

Corrige la redirection vers la page de publication

---

lib/bal-api/index.js

Ajout du status "Publié" à partir de la liste des BAL publiées.

Status Publié

---

components/header/publication.js
components/help/help-tabs/base-locale.js
components/help/help-tabs/communes.js
components/help/help-tabs/index.js
components/help/help-tabs/numeros.js
components/help/help-tabs/publication.js
components/help/help-tabs/voies.js
components/help/index.js
components/help/tuto/sidebar.js
components/help/tuto/unauthorized.js

Add documentation:  help/publication

---

components/bal/numero-editor.js

Force les suffixes en minuscule

---

lib/normalize.js
pages/bal/commune.js
pages/bal/index.js

Tri les communes et les voies par ordre alphabétique

---

components/help/index.js
pages/index.js

Add BAL guide's link to :
- index
- besoin d'aide

Add BAL guide's link

---

components/map/map.js

Menu de sélection pour le fond de carte

---

components/bal/numero-editor.js
pages/bal/voie.js

Permet de  modifier la voie attribuée à un numéro.
⚠️ Cette PR À besoin de https://github.com/etalab/api-bal/pull/199
Fix #139

Changer un numéro de voie

---

components/renew-token-dialog.js
components/settings.js
lib/bal-api/index.js

Une fenêtre s'ouvre après avoir supprimé un ou plusieurs collaborateurs

Renouvellement du token lors de la suppression d'un collaborateur

---

components/header/index.js
components/header/publication.js

Ajout d'un lien pour télécharger la BAL en csv lors de la publication

---

components/bases-locales-list/base-locale-card.js
pages/index.js

- Ajout d'un bouton pour la page ```/all```
- Ajout d'un bord sur le conteneur de bouton
- Ajout d'une condition si la BAL ne contient pas de commune

Ajout d'un bouton d’accès aux BAL depuis /all

---

components/header/publication.js

Ajout d’un message d’avertissement : 
- si la BAL contient plusieurs communes
- si la BAL ne contient pas de commune

Ajout d'un message d'avertissement lors de la publication

---

components/table-row.js

Meilleure gestion du pointeur sur les listes

---

components/footer.js
components/fullscreen-container.js
components/user-bases-locales.js
pages/index.js

- Correction du bug qui écrasait les boutons dans le navigateur safari
- Ajout d'une requête média pour faire disparaitre le ```footer``` lorsque l'écran est trop petit.

Correction de bugs sous safari

---

components/layout/fullscreen.js
components/user-bases-locales.js
pages/index.js

- Correction du bug avec le `footer` lorsqu'il n'y a pas de BAL
- Ajout d'une condition lorsqu'il n'y a pas de BAL
- Suppression de code inutile

Correction d'un bug avec le footer

---

contexts/token.js
pages/recovery.js

Utilise `window.location` à la place de `router.push`

Changement du système de redirection

---

components/sub-header/demo-warning.js
lib/bal-api/index.js
pages/new/test-form.js

- Ajout de la fonction ```createBaseLocaleTest```
- Ajout de la fonction ```updateBaseLocaleTest```

Ajout de la fonction createBaseLocaleTest et updateBaseLocaleTest

---

components/grouped-actions.js
pages/bal/voie-heading.js
pages/bal/voie.js

> fix #210  
- Ajout d'une fonction dans `grouped-action` pour remplacer une condition ternaire
- Ajout d'une fonction dans `voie` pour remplacer une condition ternaire
- Extraction d'une partie du code de `voie` dans le composant `VoieHeading`
- Utilisation du "tree-shaking" des icônes Evergreen

Simplification du code de voie.js

---

components/welcome-message.js
pages/_app.js

Ce message d'accueil à pour objectif de mieux guider l'utilisateur et éviter certaines erreurs d'utilisation récurrente comme les créations et publication de BAL déjà publié par le même utilisateur.
Fix #288 
Fix #242

Ajout d'un message de bienvenue

---

components/bal/address-editor.js
components/bal/voie-search.js
components/map/map.js

- Création de la voie si celle-ci n'existe pas encore
- Crash lorsque aucune voie n'existe
- Chargement du contexte adapté à la création (numéro/toponyme) et à la vue (commune/voie) sur laquelle elle a été effectuée
*capture*
https://user-images.githubusercontent.com/45098730/108257802-9a549b80-715f-11eb-9382-2e467c0997d4.mp4
Fix #300

Correction des problèmes liés à la création d'adresse depuis la carte

---

components/bal/voie-editor.js

Redirige vers la vue commune quand une voie est convertie en toponyme

---

components/bal/voie-editor.js

Corrige la duplication du marqueur de toponyme lorsque que la carte est déplacée

---

components/bal/address-editor.js
components/bal/numero-editor.js
components/map/editable-marker.js
components/map/map.js
contexts/markers.js

https://user-images.githubusercontent.com/56537238/109789611-cb79a500-7c10-11eb-812b-fcec9176a2c1.mov

Suggestions de numéro métrique multi-positions 

---

components/bases-locales-list/index.js
components/bases-locales-list/public-bases-locales-list.js
pages/all.js

- Ajout d'une limite pour ne pas afficher la totalité des Bases Locales
- Modification du tri : les Bases Locales sont triées par date de mise à jour

Mise à jour de la page /all

---

pages/dashboard.js
pages/dashboard/departement.js
pages/dashboard/redirection.js

**This PR is related to this one : https://github.com/etalab/adresse.data.gouv.fr/pull/787**

Adding a link button to BAL page on adresse.data.gouv.fr

---

components/bal/voie-editor.js
components/map/draw.js
components/map/editable-marker.js
components/map/map.js

- Correction d'une boucle de `useEffect` provoquant une saturation de la mémoire
- Correction de la mise à jour à chaud du tracé de la voie pour la suggestion de numéro #303 
- Correction de la sélection d'une voie en cliquant sur son tracé
- Amélioration des performances du tracé en remplaçant l'aide suivant le curseur par un message fixe en haut de la carte
https://user-images.githubusercontent.com/7040549/111643491-4c36c480-87ff-11eb-862b-ef018bcee3f3.mov
Fix #303

Correction de plusieurs problème au niveau du tracé des voies

---

components/map/hooks/bounds.js

Ajout d'un booléen pour corriger la mise à jour du fitBound et empêcher le recalcul à la modification d'un numéro
Fix #324

Correction du centrage de la camera au chargement de la page

---

lib/geo-api/index.js

Permet la gestion des codes INSEE comportant des lettres.

Gestion codes INSEE comportant des lettres 

---

components/grouped-actions.js
pages/bal/voie.js

Correction de l'erreur provoqué par le changement de voie pendant une action groupée

---

components/bal/numero-editor.js
components/map/hooks/sources.js
components/map/map.js
components/toponyme/toponyme-numeros.js
pages/bal/commune.js

Évolutions :
- Changement de la couleur de l'onglet voies/toponymes sélectionné
- Mise en avant des numéros d'un toponyme
- Classement des voies d'un toponyme par ordre alphabétique
- Ajout du nombre de numéro d'une voie dans un toponyme

Améliorations UX concernant les toponymes

---

components/grouped-actions.js

resolves #341
https://user-images.githubusercontent.com/45098730/118996621-53f22100-b988-11eb-829f-68a7bc4bb9e5.mp4

Corrige l'erreur d'attribution du type de position lors de l'édition multiple

---

components/grouped-actions.js

Corrige l'édition groupée qui ajoute des toponymes non-sélectionnés

---

pages/new/upload-form.js

Fix #345 
Il est maintenant possible d'importer un fichier CSV dont l'extension est en majuscule.

Corrige l'importation d'un fichier csv avec une extension en majuscule

---

components/bases-locales-list/base-locale-card.js
pages/new/create-form.js
pages/new/upload-form.js

Corrige le problème d'affichage du statut des Bases Adresses Locales.
Fix #360

Corrige le problème d'affichage du badge dans l'alerte "BAL déjà existante"

---

components/back-button.js
components/bal/numero-editor/select-parcelles.js
components/bal/position-editor.js
components/bases-locales-list/base-locale-card.js
components/layout/sidebar.js
components/table-row.js
lib/colors.js
package.json
pages/new/back-to-user-bals.js
pages/new/create-form.js
pages/new/demo-form.js
yarn.lock

- Création d'un nouveau composant pour remplacer le bouton de retour ([No more BackButton component](https://evergreen.segment.com/introduction/v6-migration-guide#back-button))
- Suppression de la propriété `isSolid` ([No more isSolid prop on Badge or Pill or Avatar](https://evergreen.segment.com/introduction/v6-migration-guide#is-solid))
- Ajout de la propriété `appearence` sur `communeSearch`
- Replacement des boutons de contrôle de la carte
- Suppression de la bordure du bouton du panneau latéral
- Diverses modifications visuelles (_margin, padding, taille d'icône, recentrage_)
Fix #350

Mise à Jour du framework Evergreen UI

---

.env.sample
README.md

"Mes Adresses" est un outil en ligne qui vous permet de gérer simplement vos adresses, de la constitution d’une Base Adresse Locale à sa mise à jour. Il est accessible sans compétences techniques et dispose d’un tutoriel embarqué.
Il est disponible en ligne à l'adresse [mes-adresses.data.gouv.fr](https://mes-adresses.data.gouv.fr).
[![XO code style](https://badgen.net/badge/code%20style/XO/cyan)](https://github.com/xojs/xo)
https://adresse.data.gouv.fr/data/docs/guide-mes-adresses-v4.0.pdf
- [Node.js](https://nodejs.org) 12+
- [yarn](https://www.yarnpkg.com)
Installation des dépendances Node.js
```
$ yarn
```
Lancer le serveur de développement :
```
$ yarn dev
```
Créer une version de production :
```
$ yarn build
```
Démarrer le serveur (port 3000 par défaut) :
```
$ yarn start
```
Cette …

Ajout d'un README

---

lib/bal-api/index.js
pages/bal/toponyme.js
pages/bal/voie/numeros-list.js

Ajout de notifications pour confirmer la réussite ou l’échec des actions suivantes : 
- Création / édition / suppression d’une voie
- Création / édition / suppression d’un toponyme
- Création / édition / suppression d’un ou plusieurs numéros
- Ajout d’un ou plusieurs numéros à un toponyme
- Suppression d’une Base Adresse Locale
Remplace la PR #460 
Captures d’écran :

Ajout de notifications pour les actions CRUD

---

components/layout/dashboard.js
components/sub-header/settings-menu.js
components/user-bases-locales.js
pages/404.js
pages/_error.js
pages/all.js
pages/index.js
pages/new/index.js
pages/new/upload.js

Remplacement des <Button onClick par <Button is='a'

Remplacer les boutons avec une action de redirection par de vrais liens #491

---

components/base-locale-card/index.js

issue 501 correction espace manquant dans liste des BAL 

---

components/dashboard/map.js

Le tableau de bord souffre de problème de fluidité au survol des départements, car les couches ne disposent pas de `feature.id` permettant ainsi de manipuler le style des `layers` grâce à `feature-state`. Le changement de style est donc géré grâce à une state qui provoque de lourd re-rendu de la page.
Des identifiants sont désormais générés pour les couches depuis https://github.com/etalab/contours-administratifs/pull/16. Il est en conséquence possible d'utiliser les `feature-state`.
https://user-images.githubusercontent.com/7040549/160380748-3bb5c6fc-a88d-40ee-becd-a58905d57464.mov
https://user-images.githubusercontent.com/7040549/161771293-301e82c1-750e-40dc-947d-1676676b423e.mov
Fix #541

Correction des problèmes de fluidité du survol sur le dashboard

---

components/bal/numero-editor.js
components/bal/numero-editor/select-parcelles.js
components/bal/toponyme-editor.js
components/form-master.js
components/toponyme/toponyme-heading.js
contexts/bal-data.js

Cette PR corrige #574 en initialisant la sélection des parcelles avec les parcelles du numéro ou du toponyme.
Fix #574

Corrige l'initialisation des parcelles des numéros

---

components/map/styles/plan-ign.json

Modification Link millesime plan IGN on map
Closes ticket #363

Mise à jour du lien des millésimes du plan IGN

---

components/settings/settings-form.js

resolves #676 
Cette PR corrige le bug lié à l'enregistrement du formulaire des paramètres de la BAL (nom de la BAL, ajout d'une adresse e-mail).

Corrige le bug du formulaire des paramètres de la BAL

---

components/infinite-scroll-list.js

Lorsqu'un élément d'une liste est édité, alors la liste est rechargée et la position dans cette liste est perdue.
Cette PR restaure la position de l'utilisateur dans la liste avant l'édition d'un élément.
Fix #679

Restaure la position dans la liste après l'édition d'un élément

---

components/sub-header/index.js

Un problème a été introduit lors de #685. Il n'est plus possible de renouvellement une habilitation depuis.
Cette PR corrige ce problème en s'assurant que le status de la BAL ainsi que son nombre d'adresses lui permette d'ouvrir la fenêtre de publication.

Correction le renouvellement d'habilitation

---

components/new/create-form.js
components/new/upload-form.js
pages/new.js

Les champs _Nom de la BAL_ et _Adresse email_ ne sont plus réinitialisés au changement d'onglet lors de la création d'une BAL.
[Capture vidéo 2022-09-02 18:19:51.webm](https://user-images.githubusercontent.com/45098730/188170034-2f44b6b6-d170-4497-9dd9-a822617966c2.webm)

Mise en commun des informations du formulaire de création de BAL

---

components/map/hooks/bounds.js
components/map/map.js
contexts/bal-data.js

~~## ⚠️ Ne pas merger avant [cette PR](https://github.com/BaseAdresseNationale/mes-adresses-api/pull/357) ⚠️~~
Cette PR propose de modifier le `bounds` de la carte lorsqu’une position possède plusieurs types.
Fix #665

Modification du `bounds` lorsque plusieurs type de position sont présents

---

components/voie/numeros-list.js
components/welcome-message.js
pages/accessibilite.js

Cette pull-request corrige plusieurs erreurs qui apparaissent dans la console du navigateur : 
- ` Failed prop type: Invalid prop 'isShown' of type 'string' supplied to 'Overlay', expected 'boolean'`
- `Failed prop type: The prop 'isEditionDisabled' is marked as required in 'NumerosList', but its value is 'undefined'.`
- `Received 'true' for a non-boolean attribute 'alt'.`

Corrige les erreurs affichées dans la console du navigateur

---

components/dashboard/bal-list-dialog.js
components/dashboard/map.js

Resolves #540 
- Création du composant `BALListDialog`
- Changement du curseur lors du hover sur une commune ayant une ou plusieurs BAL
- Ouverture d'une boîte de dialog listant les BAL de la commune
[Capture vidéo 2022-09-16 09:33:53.webm](https://user-images.githubusercontent.com/45098730/190564079-79df0b9e-332f-45cd-ba69-aac66792aff7.webm)

Au clique sur une commune ayant des BAL, un dialog listant les BAL s'ouvre (Dashboard)

---

components/bal/toponymes-list.js
components/bal/voies-list.js
components/settings.js
components/table-row/table-row-notifications.js
components/voie/numeros-list.js

Resolves #572
Resolves #684
[Capture vidéo 2022-09-19 19:21:11.webm](https://user-images.githubusercontent.com/45098730/191054281-613faebe-1666-44d6-9ad3-db8e27273450.webm)

Indique si les adresses d'une voie sont toutes certifiées

---

components/new/create-form.js
components/new/demo-form.js
components/new/upload-form.js

En cas de problème rencontré au moment de la soumission des formulaires, aucune erreur n'est récupérée bloquant l'utilisateur sur le formulaire.
Affiche à l'utilisateur les erreurs pouvant être rencontrées au moment de la soumission des formulaires de création.

Gestion des erreurs de soumissions des formulaires

---

components/help/help-tabs/voies.js

La PR https://github.com/BaseAdresseNationale/mes-adresses/pull/751 n'a pas été ajouté à la documentation interactive de Mes Adresses. On pourra ajouter cette fonctionnalité à l'onglet "Voie" '/components/help/help-tabs/voies.js)

Ajouter la conversion en toponyme à la documentation #759

---

.env.sample
package.json
server/index.js
yarn.lock

La variable env PORT n'était pas pris en compte pour le server express.
Avec l'ajout de dotenv on peut changer le port de mes-adresses via la var env PORT

Ajouter dotenv pour var env PORT

---

components/overlay.js
components/sub-header/index.js
components/welcome-message.js
contexts/bal-data.js
contexts/token.js
hooks/habilitation.js
layouts/editor.js

Avec le lien administrateur, on peut rester quelque secondes voir minutes en 'édition impossible'.
https://github.com/BaseAdresseNationale/mes-adresses/issues/735
- Remplacement du bouton 'édition impossible' par 'chargement' tant que la bal n'est pas chargé
- Ajout d'un overlay sur toutes l'appli tant que la bal n'est pas chargé

Ajouter un overlay pour griser l'écran tant que tout n'est pas charger

---

components/bal/toponymes-list.js
components/bal/voies-list.js
components/infinite-scroll-list.js
components/map/numeros-markers.js
components/map/toponyme-marker.js
components/sub-header/index.js
components/sub-header/settings-menu.js
components/table-row/table-row-edit-shortcut.js
components/trash/list/items-deleted-list.js
components/trash/restore-voie/index.js
components/trash/restore-voie/list-numeros-deleted.js
components/trash/restore-voie/row-numero-deleted.js
components/trash/table-row-deleted/index.js
components/trash/table-row-deleted/table-row-action-deleted.js
components/trash/trash.js
components/voie/numeros-list.js
hooks/trash.js
layouts/editor.js
lib/bal-api/index.js
pages/bal.js

https://github.com/BaseAdresseNationale/mes-adresses/issues/528
https://github.com/BaseAdresseNationale/mes-adresses/issues/529
https://github.com/BaseAdresseNationale/mes-adresses/issues/772
- Création de la corbeille accessible avec un petit button dans la paramètre
https://github.com/BaseAdresseNationale/mes-adresses-api/pull/382

Ajout de la Corbeille pour les voies/toponymes/numeros

---

components/bal/habilitation-infos.js

Issue : https://github.com/BaseAdresseNationale/mes-adresses/issues/803

fix: date format is not in french if the browser locale is different

---

components/new/upload-form.js
package.json
yarn.lock

https://github.com/BaseAdresseNationale/validateur-bal/issues/76
https://github.com/BaseAdresseNationale/api-depot/issues/89
https://github.com/BaseAdresseNationale/validateur-bal/pull/75

update validator 2.15.0

---

components/map/hooks/hovered.js
components/map/map.js
components/map/popup-feature/popup-feature-numero.js
components/map/popup-feature/popup-feature-voie.js
components/map/popup-feature/popup-feature.js

https://github.com/BaseAdresseNationale/mes-adresses/issues/515

Ajouter popup au survole des features du layer de tuile

---

components/comment.js

https://github.com/BaseAdresseNationale/mes-adresses/issues/818

Add placeholder to comments

---

components/map/map.js
components/map/numeros-markers.js
components/settings.js
components/settings/bal-settings-form.js
components/settings/user-settings-form.js
components/sub-header/settings-menu.js
contexts/local-storage.js
contexts/map.js
contexts/settings.js

Contexte:
- https://github.com/BaseAdresseNationale/mes-adresses/issues/530
- https://github.com/BaseAdresseNationale/mes-adresses/issues/499
Fonctionnalités :
- Menu préférences utilisateur dans les paramètres. Les préférences utilisateurs sont enregistrées dans le local storage
- Mode daltionien (En attente de la PR des tiles)

Ajoute les préférences utilisateur et le mode daltonien

---

components/bal/toponyme-editor.js
components/bal/voie-editor.js

https://github.com/BaseAdresseNationale/mes-adresses/issues/831

correct bug nom toponyme/voie pas maj

---

components/habilitation-process/index.js
hooks/publish-process.js

https://github.com/BaseAdresseNationale/mes-adresses/issues/828

Garde le statut brouillon jusqu'à la validation d'une habilitation

---

components/commune-search/commune-search.js
components/form-input.tsx
types/base-locale.ts

- liste des commune décalé on first try

fix: input autocomplete position

---

components/bal/voie-editor.js

- langue régionale + tracé = léger overlap des bouton > ajouter un peu de padding sur enregistrer might fix it

Fix style overlap button

---

components/bal/numero-editor.js
components/certification-button.js
components/comment.js
components/grouped-actions.js
components/map/hooks/bounds.js
components/settings/bal-settings-form.js
components/settings/user-settings-form.js

- https://github.com/BaseAdresseNationale/mes-adresses/issues/861
- Fix des boutons sticky
- Fix zoom sur les voies métriques

évolutions demandées

---

components/help/help-tabs/publication.js

Mise à jour du besoin d'aide avec le nouveau status En attente d'habilitation.

Mise à jour du besoin d'aide avec le nouveau status

---

.github/workflows/node.js.yml
package.json

Ajout du build avec node v18 et v20

ci: add build node 18 and 20

---

components/bal/numero-editor.tsx
components/map/editable-marker.tsx
contexts/markers.tsx

En métrique, que le numéro soit ajouté automatiquement

feat: autocomplete numero voie metrique

---

components/user-bases-locales.tsx
lib/openapi/services/BasesLocalesService.ts

- Une commune voit toujours une BAL en conflit supprimée
https://github.com/BaseAdresseNationale/mes-adresses-api/pull/454

feat: get only exist bal in user home

---

package.json
yarn.lock

- Correction du bug d'interprétation champ uid_adresses

validateur v2.19.1

---

components/habilitation-process/accepted-dialog.tsx
components/habilitation-process/authenticated-user.tsx

fix: elu mandat

---

lib/openapi/models/ExtendedBaseLocaleDTO.ts

Changement de la class ExtendedBaseLocaleDTO

fix: etendedBasesLocaleDTO change

---

hooks/habilitation.ts
pages/bal/[balId]/index.tsx

Il y a un message d'error au chargement les bal `en cour de mise a jour`

hotfix: request habilitation bal outdated

---

components/new/alert-published-bal/alert-puslished-bal-moissoneur.tsx

migratio: moissonneur postgres

---

package.json

Scalingo essaye de faire tourner avec node 23.
Donc on fix sur node 22

infra: package.json engine node 22

---

components/bal/toponyme-editor.tsx
components/bal/voie-editor.tsx
components/comment.tsx
components/langues-regionales-form/index.tsx
components/voie/voie-heading.tsx

- Lorsqu'il y a des langue alternatif, le header des voie est en ligne
- On n'affiche pas les erreurs des langue régionales et des commentaires

Fufeck fix lang regional bug

---

components/new/create-form.tsx

On ne capte pas l'erreur 504 et donc la création d'une grande ville mouline lorsqu'elle timeout
-> On n'attends le retoure de populate et on lance is_populating dans tous les cas

fix: create bal waiting populate

---

components/new/alert-other-bal.tsx
components/new/alert-published-bal.tsx
components/new/create-form.tsx

- Ajout d'un message lors du populate à la création d'une BAL

feat: add msg on populate bal

---

components/bases-locales-list/index.tsx

feat: add bal searchbar

---

components/signalement/purge-expired-signalements-dialog.tsx
components/signalement/signalement-list.tsx
lib/utils/signalement.ts
pages/bal/[balId]/signalements/index.tsx

Ajoute une tâche pour purger les signalements expirés : https://www.loom.com/share/0d6f4ae1e5814815aa0d53ec64f7eaff

feat: add batch task to purge expired signalements

---

components/bal/certification-infos.tsx
components/dialog-warning-action.tsx
components/table-row/table-row-actions.tsx
contexts/bal-data.tsx
lib/openapi-api-bal/services/BasesLocalesService.ts
lib/openapi-api-bal/services/VoiesService.ts
pages/bal/[balId]/index.tsx
pages/bal/[balId]/voies/index.tsx

La fonctionnalité pour certifier tous les numeros est utilisé a tord et a travers
Suppression de la certification total
Ajout de la cettification voie par voie

feat: certify numeros voie by voie
