BaseAdresseNationale/mes-adresses

.env.sample, components/header.js
Ce nouveau bouton permet d'être redirigé vers l'outil de publication de Base Adresse Locale de `adresse.data.gouv.fr`.
⚠️ En attente de https://github.com/etalab/adresse.data.gouv.fr/pull/332
=> Ajout du bouton "Publier"

components/bal/voie-editor.js
Quand un nouvel `editingId` est assigné, `VoieEditor` désactive le marqueur de la carte quand la voie n'est pas un toponyme. Cependant `MarkerContextProvider` est lui aussi déclenché par `editingId` et vient ré-activer le marqueur.
Ajouté `enabled` au `useEffect` de `VoieEditor` permet d'empêcher ce comportement.
Fix #7
=> Corrige l'édition des voies

components/bal/numero-editor.js
Permet de définir `suffixe` à `null` afin de pouvoir le supprimer.
Fix #6
=> Corrige l'édition des suffixes

components/header.js, lib/bal-api/index.js
Previously the client was downloading the CSV file and give a local URL to the user.
In production, this behavior is blocked by Safari and by uBlock Origin.
The new behavior is just a link.
=> Replace CSV download behavior

components/table-row.js
Permet de renommer une voie, un toponyme ou un numéro directement en cliquant  sur le label de la liste.
=> Cliquer sur le label pour éditer

components/map/map.js
Il peut arriver que l'événement de clique soit déclenché par un layer du fond de carte. Cette PR vérifie que la `feature` est bien une adresse et comporte la propriété `idVoie`?
=> Corrige la sélection de numéro

components/commune-search/commune-search.js
Certaines communes sans département comme "Alo - 98611" faisaient casser la recherche de commune. Ce correctif filtre ces communes.
=> Corrige la recherche de commune

components/map/hooks/bounds.js
- La carte ne recentre plus si la voie est la même afin d'éviter de perturber l'utilisateur après un ajout ou une suppression de numéro.
- La carte ne recentre plus sur le marqueur
- Le rayon du buffer de fitbounds a été réduit afin de ne plus afficher une image dégradée
=> Corrige les fitBounds intempestifs 

components/bal/commune-editor.js, components/bal/numero-editor.js, components/bal/position-editor.js, components/bal/voie-editor.js, components/breadcrumbs.js, components/commune-search/commune-search-field.js, components/commune-search/commune-search.js, components/header.js, components/layout/fullscreen.js, components/map/control.js, components/table-row.js, contexts/bal-data.js, contexts/token.js, hooks/fuse.js, pages/_app.js, pages/bal/commune.js, pages/bal/index.js, pages/bal/settings.js, pages/bal/voie.js
- Déclare les `props` oubliées dans `propTypes`
- Attribue des valeurs par défaut à toutes les `props` optionnelles.
- Ajoute les `props` oubliées dans les `Hooks` React
=> Corrige les différents problèmes de linter

pages/new/create-form.js, pages/new/upload-form.js
Le navigateur chrome détecte les mots `Nom` et `Adresse` dans le champ texte du formulaire de création de BAL et autocomplète avec l'adresse de l'utilisateur. La propriété `autocomplete='off'` n'étant pas prise en compte par chrome, nous le forçons à laisser le champ vierge grâce à `new-password`
=> Désactive l'autocomplétion de chrome sur le formulaire de création de BAL

components/user-bases-locales.js
Si une BAL n'existe plus en base alors celle-ci provoque une erreur qui bloque la récupération des autres BAL.
=> Corrige la récupération des BAL de l'utilisateur

components/bal/address-editor.js, components/bal/numero-editor.js, components/comment.js, components/help/help-tabs/numeros.js, components/table-row.js, pages/bal/voie.js
Offre la possibilité d'ajouter des commentaires dans l'édition des numéros.
Un numéro commenté se distingue par un ![Capture d’écran 2019-06-21 à 11 21 52](https://user-images.githubusercontent.com/7040549/59912676-cbbf1600-9416-11e9-82b7-4be5f810b56d.png)
Il est possible de voir le commentaire en survolant cet icon.
Le champ de texte prévu pour les commentaires est limité à 5000 caractères.
⚠️ Cette PR est dépendante de https://github.com/etalab/api-bal/pull/70 qui met à jour l'API
=> Ajouter des commentaires aux numéros

components/bases-locales-list.js
Lorsque qu'un BAL est publiée, le bouton "supprimer" ne sera plus afficher afin d'éviter une suppression par erreur.
=> Ne plus afficher le bouton "supprimer" pour une BAL publiée

components/bases-locales-list/base-locale-row.js, components/bases-locales-list/index.js, components/header/index.js, components/header/publication.js, pages/_app.js
Cette PR ajoute la gestion du nouveau statut "Prête à être publiée".
Il permet plusieurs choses:
- L'utilisateur peut la reconnaitre facilement dans sa liste de BAL
- Une BAL avec ce statut ne peut plus être supprimée
- Il nous permet de reconnaitre les BAL qui serait prête à être publiée et ainsi de contacter l'utilisateur afin de savoir pourquoi il ne l'a pas encore publié
Le header permet de changer le statut d'une BAL à la demande si celle-ci n'est pas publiée.
⚠️[Attendre la mise à jour de l'api-bal](https://github.com/etalab/api-bal/pull/87)
Fix #87
=> Nouveau statut "Prête à être publiée"

components/bal/address-editor.js, components/bal/numero-editor.js, components/bal/voie-editor.js, components/comment.js, components/layout/sidebar.js, pages/_app.js, pages/bal/voie.js
- Ouverture de la barre latérale lorsque le numéro est édité
- Lors de l'édition d'un numéro, les autres numéros sont cachés
- Transformation de l'icône "annuler" en bouton :
- L'ouverture de l'éditeur de voie ferme l'éditeur de numéro et vice-versa
=> Modification comportement barre latérale

components/header/index.js, components/map/map.js, components/settings.js, contexts/bal-data.js, contexts/settings.js, contexts/token.js, lib/utils/email.js, pages/_app.js, pages/bal/index.js, server/routes.js
Cette PR a pour effet de supprimer la page `/settings` et de la remplacer par un menu latéral. Cette évolutions prépare l'arrivée de futurs nouveaux paramètres pour lesquels le changements de page aurait détérioré l'expérience utilisateur.
- Rafraichissement dynamique des meta données de la base adresse locale
- Sauvegarde possible uniquement si des changements sont détectés
- Amélioration de la validation des champs
=> Remplace la page /settings par un menu latéral

components/bal/address-editor.js, pages/bal/index.js
Si un numéro est ajouté dans la voie `B` alors que la voie `A` est sélectionnée alors les numéro affichés sur la carte et le menu latéral se mettent à jour correctement mais pas la voie sélectionné reste la voie `A`.
Ce correctif redirige l'utilisateur vers la bonne voie.
=> Correction de la mise à jour de la voie lorsque qu'un numéro n'est pas ajouté dans la voie par défaut 

components/header/index.js, components/settings.js, components/user-bases-locales.js, pages/index.js, pages/new/index.js, pages/new/test-form.js
Permet aux utilisateurs d'essayer l'éditeur sans fournir d'adresse email ou nommer leur BAL.
La publication ainsi que la modification des paramètres de la Base Adresse Locale sont désactivés pour les BAL de test.
⚠️ Cette PR nécessite https://github.com/etalab/api-bal/pull/200
Fix #133
=> Création de Base Adresse Locale de test

pages/bal/voie.js
Une variable temporaire n'était pas réinitialisée lors du changement de voie ce qui avait pour effet de persister le nom de la voie précédente.
=> Correction du changement de nom de la voie lors d'un changement de voie depuis la carte

DEVELOPER_NOTES.md, components/bal/draw-editor.js, components/bal/numero-editor.js, components/bal/voie-editor.js, components/map/control.js, components/map/draw.js, components/map/editable-marker.js, components/map/hooks/bounds.js, components/map/hooks/layers.js, components/map/hooks/sources.js, components/map/layers/voies.js, components/map/map.js, contexts/bal-data.js, contexts/draw.js, contexts/marker.js, lib/voie.js, package.json, pages/_app.js, pages/bal/commune.js, pages/bal/voie.js, yarn.lock
Cette nouvelle fonctionnalité permet d'indiquer si une voie utilise une numérotation métrique. Offrant ainsi la possibilité à l'utilisateur de tracer ses voies sur la carte afin d'obtenir une assistance spécifique pour la numérotation de ce type de voie.
En quelques cliques, l'utilisateur peut utiliser la carte afin de tracer la voie. Le fond de carte passera automatiquement en vu satellite afin de facilité le dessin, notamment dans le cas d'une création de voie. Une fois terminé, le précédent fond de carte utilisé sera chargé.
Lors de la création des adresses, l'éditeur suggérera à l'utilisateur quel numéro choisir en fonction de sa position sur la voie. L'utilisateur pourra toutefois choisir le numéro qui lui semble juste.
⚠️ Cette PR à besoin de …
=> Ajout de la numérotation métrique

components/bal/voie-editor.js, pages/bal/commune.js, pages/bal/voie.js
Lors de l'édition d'une voie sans numéro, il est possible de cocher la case permettant d'indiquer que c'est un toponyme.
capture
=> Possibilité de changer une voie sans numéro en toponyme

pages/new/create-form.js, pages/new/index.js, pages/new/test-form.js
- Suppression de l'indice "Vous pourrez ajouter plusieurs communes à la Base Adresse Locale plus tard."
- Ajout du terme "Démonstration" afin de mieux qualifier la création des BAL de tests.
=> Reformulation du formulaire de création des BAL

.env.sample, components/help/help-tabs/base-locale.js, components/retrieve-bal-acccess.js, contexts/token.js, lib/tokens.js, next.config.js, pages/_app.js, pages/index.js, pages/recovery.js
Création de la page `/recovery` qui permet de migrer les Bases Adresses Locales des utilisateurs du domaine `editeur.adresse.data.gouv.fr` vers `mes-adresses.data.gouv.fr`
=> Migration des Bases Adresses Locales entre les domaines

components/map/hooks/layers.js, components/map/map.js
Quand aucune voie ni numéro n'est affiché sur la carte, le chargement de leurs layer provoqué un "freeze" de la carte, empêchant le changement de fond de carte.
Ce correctif permet de ne charger que les sources et layers disponible en fonction des features du geojson chargé dans MapBoxGL.
=> Corrige le chargement des sources et des layers empêchant le changement de fond de carte

.env.sample, components/help/help-tabs/base-locale.js, components/retrieve-bal-acccess.js, contexts/token.js, lib/tokens.js, next.config.js, pages/_app.js, pages/index.js, pages/recovery.js
Création de la page /recovery qui permet de migrer les Bases Adresses Locales des utilisateurs du domaine editeur.adresse.data.gouv.fr vers mes-adresses.data.gouv.fr
Reverted PR #234
=> Migration des Bases Adresses Locales entre les domaines [retry]

components/help/index.js
Depuis le guide interactif, le lien renvoyant vers le guide de l'éditeur est obsolète
- Remplacé par un lien vers la page des guides
=> Lien vers le guide de l'éditeur obsolète

components/layout/sidebar.js, components/map/index.js, components/sub-header/demo-warning.js, components/sub-header/index.js, pages/_app.js
- Ajout d'un bandeau pour prévenir l'utilisateur qu'il se trouve sur une Base Adresse Locale de démonstration.
- Ajout d'un bouton et d'un formulaire permettant de transformer une Base Adresse Locale de démonstration en Base Adresse Locale publiable.
=> Transformation de BAL de démonstration

.env.sample, components/help/help-tabs/base-locale.js, components/sub-header/index.js, contexts/token.js, lib/adresse-backend/index.js, lib/bal-api/index.js, lib/geo-api/index.js, next.config.js, package.json, pages/recovery.js, yarn.lock
L'ancienne méthode utilisant `next-runtime-dotenv` est obsolète depuis Next.js 9.4.
Nouvelle documentation : https://nextjs.org/docs/basic-features/environment-variables
=> Gestion native des variables d'environnement par Next.js

components/bases-locales-list/base-locale-card.js, components/demo-bal-alert.js, components/settings.js, components/sub-header/demo-warning.js, components/sub-header/index.js, lib/bal-api/index.js, pages/_app.js, pages/new/demo-form.js, pages/new/index.js, pages/new/test-form.js
- Modification du message dans le bandeau : 
- Modification du message dans la boite de dialogue : 
- Modification de la fonction `createBaseLocaleDemo`
- Changement de nom pour `updateBaselocaleTest` -> `transformToDraft`
- Suppression des `isTest` et remplacement par `Demo`
=> Modification du message sur les Bases Adresses Locales de démonstration

components/bases-locales-list/index.js, components/user-bases-locales.js, lib/sort-bal.js, pages/all.js
> fix #271 
Sur la page d'accueil, les Bases Adresse Locales sont désormais triées par date de mise à jour.
Sur la page `all`, elles sont triées par ordre alphabétique.
=> Tri de la liste des Bases Adresse Locales par date de mise à jour ou par nom

components/bal/numero-editor.js, hooks/input.js
Resolves #283 
- Ajout de l'attribut `name` aux champs du formulaire
- Utilisation de `useState` à la place de `useInput`
https://user-images.githubusercontent.com/45098730/106280658-7d066e80-623e-11eb-8143-8e2905980fae.mp4
=> Résout le problème d'assignation du numéro au clique lors du mode édition

pages/bal/voie-heading.js, pages/bal/voie.js
Le nom de la voie n'est pas mis à jour lors d'un changement d'une voie à une autre car le composant s'est initialisé avec la première voie sélectionnée.
=> Corrige la mise à jour du nom de la voie après un changement de voie

components/map/hooks/layers.js, components/map/layers/voies.js, components/map/map.js, pages/bal/voie-heading.js, pages/bal/voie.js
- Cache le complément de voie sur la carte quand l'option est désactivée (Fix #298)
- Afficher le complément de voie dans l'entête de la voie
=> Corrections concernant le complément du nom de voie

pages/new/back-to-user-bals.js, pages/new/upload-form.js
Ajout d'un message lors de la création d'une BAL grâce à l'import de fichier CSV, invitant les utilisateurs possédant déjà une BAL prête à être publiée à le faire directement via adresse.data.gouv.fr sans utiliser l'éditeur comme passe plat.
- Réagencement du formulaire de création de BAL (import CSV) afin de mieux séparer le message et le formulaire
- Modification de la couleur et du texte du bouton de retour aux BAL de l'utilisateur afin de le rendre plus discret mais plus compréhensible.
=> Message invitant à publier directement un fichier CSV

components/map/control.js, components/map/map.js, components/map/numero-marker.js, components/map/toponyme-marker.js, components/table-row.js, contexts/bal-data.js, pages/bal/commune.js, pages/bal/voie-heading.js, pages/bal/voie.js
Lorsqu'une édition ou une création est en cours sur une adresse, toute autre action d'édition sur un autre object est bloquée.
La possibilité de lancer plusieurs éditions ou création de manière simultanée provoque un nombre conséquent de bug pouvant aller jusqu'à faire planter l'application.
Cette PR rigidifie légèrement la fluidité de l'expérience utilisateur, mais assure un fonctionnement cohérent et corrige bon nombre de comportements improbable pouvant provoquer des erreurs. 
Remplace #305 
Fix #301
Fix #306
=> Désactive l'édition quand une édition ou une création est déjà en cours

lib/adresse-backend/index.js
Ajouts d'une condition pour éviter tout problème avec `backend.adresse.data.gouv.fr` après l'incendie OVH.
=> Ajout d'une condition sur backend-adresse

components/map/styles/vector-cadastre.json
- Remplacement de la font `Lato` par `Noto Sans`
=> Correction du fond de carte cadastral

components/map/hooks/bounds.js
Lors de l'ajout de numéro sur de longue voie, la carte se recentre sur l'assemble de la voie après chaque modification. Ce comportement est gênant car il modifie le zoom et déplace la carte obligeant l'utilisateur à recommencer son placement pour ajouter un nouveau numéro à la suite du premier.
------
Cette PR permet que le recentrage de la carte ne s'effectue que si le contexte (voie ou commune) change.
=> Modification du recentrage automatique de la carte

components/bal/address-editor.js, components/bal/draw-editor.js, components/bal/numero-editor.js, components/bal/numero-editor/select-parcelles.js, components/bal/position-editor.js, components/bal/toponyme-editor.js, components/input-label.js, components/map/map.js, components/map/style-selector.js, contexts/map.js
Il nous a été remonté par des utilisateurs que l'affichage forcé de la couche cadastrale lors de l'édition d'un numéro pouvait représenté une gêne important quant à la lisibilité de la carte. De plus, le nombre de message d'aide contextuel dans le formulaire sont devenu trop nombre est perturbent également la lecture du formulaire.
- Association des parcelles à une adresse uniquement lorsque les parcelles sont affichées
- Bouton "Afficher le cadastre" directement accessible depuis le formulaire (visible seulement quand le cadastre n'est pas affiché)
-  Messages d'aide maintenant disponible au survole de l'aide d'outil "?"
- Correction des textes d'aide pour la sélection des parcelles et des positions qui font maintenant la distinction entre toponyme et numéro
- La state `showCadastre` a …
=> Amélioration UX de l’association des parcelles cadastrale

components/bases-locales-list/base-locale-card.js, components/bases-locales-list/index.js, lib/bal-api/index.js, pages/new/alert-published-bal.js, pages/new/create-form.js, pages/new/upload-form.js
Cette PR vient apporter des modifications et des corrections suite à #349 
- Simplification de la gestion des BAL appartenant à l'utilisateur dans le composant `<BaseLocalCard />`
- Renommage de différentes variables et fonction
- Reprise du wording
- Désactive la suppression de BAL lorsque `onRemove` n'est pas défini
=> Correction de l'affichage de l'alerte à la création d'une BAL déjà existante

next.config.js, package.json, yarn.lock
Mise à jour de NextJs de la version 10.0.3 vers la version 11.0.1
Cette mise à jour nécessite également la mise à jour des librairies suivantes : 
> Mise à jour de `react` de la version 17.0.1 vers la version 17.0.2
> Mise à jour de `react-dom` de la version 17.0.1 vers la version 17.0.2
> Mise à jour de `fs-extra` de la version 9.0.1 vers la verison 10.0.0
> 
> Mise à jour de `webpack` de la version 4 vers la version 5
> 
> Mise à jour de `next.config.js` pour supporter webpack 5
Lien vers la documentation de mise à jour : [Upgrade Guide | Next.js](https://nextjs.org/docs/upgrading)
=> Mise à jour de NextJs et de ses dépendances 

pages/all.js
Depuis #365 le composant `<BaseLocaleCard />` a besoin d'avoir accès au `localestorage` de navigateur de l'utilisateur. Ce composant doit donc être chargé côté client.
Utilisation de `next/dynamic` afin de charger la liste des BAL côté client.
=> Correction du chargement de la page /all

components/uploader.js, pages/new/upload-form.js
Cette PR permet d'empêcher le dépôt de fichier CSV comportant plusieurs communes. Ceci afin de limiter la création de BAL multi-communales qui ne seront bientôt plus supportées par l'outil.
Fix #378 
---
- Fichier trop volumineux
- Fichiers multiple
=> Empêche le dépôt d'un fichier CSV comportant plusieurs communes

components/help/help-tabs/base-locale.js, components/help/help-tabs/communes.js, pages/bal/index.js
La gestion des BAL multi-communales étant bientôt obsolète, cette PR complète #379 en empêchant également l'ajout d'une commune à une BAL existante.
Ces modifications ont pour objectifs de préparer la migration vers la gestion de Bases Adresses Locales Communale.
- Bouton "Ajouter une commune" supprimé lorsque la BAL possède plusieurs communes
- Affiche d'un message d'avertissement pour les BAL avec plusieurs communes
- Mise à jour de la documentation
https://user-images.githubusercontent.com/7040549/130641708-211492a2-755b-4dbf-9459-835e0efdca8b.mov
=> Désactive l'ajout de commune à une BAL existante

components/map/styles/ortho.json
Suppression du proxy Etalab.
Il n'est plus nécessaire.
Avantages :
plus besoin d'espace de stockage pour le cache
un composant en moins à maintenir
Inconvénient :
On perd l'HTTP/2 pour le moment
Lié à etalab/adresse.data.gouv.fr#863
=> Change l'URL du fond de carte photos aériennes IGN

components/map/styles/ortho.json
Certain utilisateur ont exprimés le besoin de connaitre la date de mise à jour des photographies aérienne utilisées pour le fond de carte.
L'ajout du lien vers la documentation de la BD Ortho permet aux utilisateurs de retrouver toutes les informations dont ils ont besoin concernant le fond de carte.
=> Ajout d'un lien vers la source de la carte "photo aérienne"

components/user-bases-locales.js
Des utilisateurs ont remontés que la page d'accueil charger indéfiniment. Ce problème vient du fait qu'au moins une de leur BAL renvoi une erreur 404. Cette erreur est mal récupéré et empêche le changement d'affichage de l'interface.
Cette PR corrige la récupération de l'erreur 404 afin de supprimer le chargement afficher à l'utilisateur. 
La promesse étant en réalité résolu dans le `Promise.all` et non dans le `try/catch`, il suffit de forcer la résolution de la promesse dans le `map`.
=> Corrige le chargement des BAL de l'utilisateur

components/map/numero-marker.js
=> Correction de la position de l'icône de certification sous Safari

components/bal/numero-editor.js
Cette PR propose de transformer le type de la valeur du champ `numero` en chaine de caractère pour éviter qu'il soit considéré comme un booléen.
Elle corrige ensuite un avertissement des outils de développement par rapport à un champ du formulaire qui ne peut être `null`.
Fix #395
=> Corrige le problème d’affichage du numéro zéro

components/certification-message.js, components/welcome-message.js
Les messages de bienvenu et de certification automatique s'affiche en mode consultation.
Ces messages ne s'affiche désormais que si l'utilisateur dispose d'un `token`.
=> Cache les messages à destinations de l'édition en mode consultation

contexts/bal-data.js, lib/bal-api/index.js
⚠️ **Cette PR a besoin de cette [Pull Request](https://github.com/etalab/api-bal/pull/297) pour fonctionner.** ⚠️
Certains utilisateurs stockent des informations sensibles dans les commentaires de leur Base Adresse Locale.
Les Bases Adresses Locales étant accessibles publiquement sans autorisation spéciale, il est préférable d'afficher les commentaires uniquement aux utilisateurs de la Base Adresse Locale disposant du jeton d'administration.
Fix #394
=> Masque les commentaires des numéros en mode consultation

components/help/help-tabs/base-locale.js, components/help/help-tabs/numeros.js, components/help/help-tabs/toponymes.js
À l'ouverture de certains onglets de la partie "Besoin d’aide ?", une erreur apparaissait en console concernant l'imbrication des balises HTML. 
(` <div> cannot appear as a descendant of <p>` ou ` <p> cannot appear as a descendant of <p>`) 
Cette PR modifie quelques éléments pour faire disparaitre les erreurs présentées ci dessus.
- Suppression d'un élément `TabList` inutile
- Modification d'éléments `Paragraph` (p)  en `Pane` (div)
Fix #402
=> Corrige le message d'erreur `validateDOMNesting` dans l'élement "Besoin d'aide ?" 

components/bal/numero-editor.js
À l'ouverture de l'élément `AddressEditor`, un message d'erreur apparaît en console indiquant : 
`The prop isCertified is marked as required in CertificationButton, but its value is undefined `
Cette PR ajoute une valeur par défaut à la propriété `isCertified` de l'élément `CertificationButton` lorsqu'il n'y a pas de valeur initiale, c’est-à-dire lors de la création d'un numéro.
Fix #404
=> Corrige le message d'erreur de la propriété `isCertified` non définie

components/bal/numero-editor.js
L'API-BAL retourne un objet avec une structure différente que l'on appelle `getNumeros` ou `getNumerosToponyme` .
Toponyme ayant besoin du nom de la voie pour afficher son nom ainsi que pour classer les numéros par nom de voie.
Le typage de la propriété "voie" n'étant pas identique selon l'appel, une erreur apparaissait en console : 
`Invalid prop initialValue.voie of type object supplied to NumeroEditor, expected string`
Nous avons donc décidé d'utiliser `oneOfTypes` exceptionnellement pour éviter une modification qui couterai beaucoup d'appels à l'API.
- Ajout de la propTypes `oneOfType`
- Ajout de commentaire pour justifier son utilisation
fix #405
=> Corrige le problème de typage de "voie" dans "numeroEditor"

components/settings.js, contexts/token.js
Cette PR corrige un message d'erreur dans la console en mode consultation : 
`Warning: Failed prop type: Invalid prop token of type boolean supplied to Publication, expected string.` 
À l'ouverture d'une Base Adresse Locale en mode consultation (sans jeton d'administration), le contexte du token vérifie que le jeton correspondant à la Base Locale est bien présent. S’il ne l'est pas, le token passait à `false` et était donc considéré de type "booléen".
Désormais, le jeton est défini à `null`  si l'utilisateur n'est pas administrateur de la Base Locale consultée.
Fix #401
=> Corrige le message d'erreur sur le typage de `token`

components/header.js, components/help/index.js, components/sub-header/index.js
Le bouton d'accès à l'aide interactive se situe actuellement à droite de l'en-tête d'une BAL. L'espace disponible sur cette l'en-tête étant limité et voué à évoluer, il est préférable de déplacer ce bouton afin de libérer de l'espace mais aussi le rendre plus visible.
- Déplace le bouton d'accès à l'aide interactive dans la barre de navigation.
- Ajout d'icones illustrant l'aide et la documentation
-----
=> Déplace l'accès à l'aide interactive 

package.json, yarn.lock
Depuis le mois de juillet, la librairie Evergreen a connue plusieurs mises à jour.
Ces mises à jour corrigent deux problèmes listés dans [l'audit des erreurs et warnings de mes-adresses](https://github.com/BaseAdresseNationale/mes-adresses/issues/410) .
`Warning: componentWillReceiveProps has been renamed, and is not recommended for use.`
et
`Warning: The value prop is required for the <Context.Provider>. Did you misspell it or forget to pass it?` ([Issue #403](https://github.com/BaseAdresseNationale/mes-adresses/issues/403))
Fix #403
=> Mise à jour de Evergreen-ui vers la version 6.4.0

package.json, yarn.lock
Mise à jour de la librairie [react-dropzone](https://github.com/react-dropzone/react-dropzone) : 
_de la version 10.1.10 vers la version 11.4.2_
[Changelog](https://github.com/react-dropzone/react-dropzone/releases)
⚠️ Changements notables dans la version [11.0.0](https://github.com/react-dropzone/react-dropzone/releases/tag/v11.0.0)  ⚠️
=> Mise à jour de la librairie `react-dropzone` 

package.json, yarn.lock
Mise à jour de la librairie [date-fns](https://github.com/date-fns/date-fns) : 
_de la version 2.16.1 vers la version 2.24.0_
[Changelog](https://github.com/date-fns/date-fns/releases)
=> Mise à jour de la librairie `date-fns`

.github/workflows/node.js.yml, README.md, package.json
Version minimale : 14
Versions utilisées par GitHub Actions : 14 et 16
=> Fin de support de Node.js 12

package.json, yarn.lock
Mise à jour de la librairie [etalab/bal](https://github.com/BaseAdresseNationale/bal)
_de la version 1.2.0 vers la version 1.5.1_
[Changelog](https://github.com/BaseAdresseNationale/bal/releases)
=> Mise à jour de la librairie `etalab/bal`

package.json, yarn.lock
Mise à jour du framework [NextJs](https://github.com/vercel/next.js)
_de la version 11.0.1 vers la version 11.1.2_
[Changelog](https://github.com/vercel/next.js/releases)
--- 
Mise à jour de [next/bundle-analyzer](https://github.com/vercel/next.js/tree/canary/packages/next-bundle-analyzer) : 
_de la version 10.1.2 vers la version 11.1.2_
=> Mise à jour de NextJs 11.1.2

components/map/nav-control.js, package.json, yarn.lock
Mise à jour de la librairie [react-map-gl](https://github.com/visgl/react-map-gl) : 
_de la version 5.2.7 vers la version 5.3.17_
[Changelog](https://github.com/visgl/react-map-gl/releases)
---
Mise à jour de la librairie [react-map-gl-draw](https://github.com/uber/nebula.gl) :
~~_de la version 0.19.2 vers la version 0.23.8_~~
_de la version 0.19.2 vers la version 0.21.1_
**Note :**
_La dernière version de `react-map-gl-draw` ne prend plus en charge l’édition d’un tracé, nous utilisons donc la dernière version fonctionnelle en attendant un correctif ([source](https://github.com/uber/nebula.gl/issues/580))_
[Changelog](https://github.com/uber/nebula.gl/releases)
---
Correction d’une propriété CSS (Les contrôles de la carte s’étant déplacés après la mise à jour)
=> Mise à jour des librairies `react-map-gl` & `react-map-gl-draw`

pages/bal/commune.js
L’éditeur reste en mode édition lorsque l’on ajoute une voie.
Cette PR remet la valeur de `isEditing` à `false` pour sortir du mode édition une fois la voie ajoutée.
=> Corrige la fermeture du mode édition après l’ajout d’une voie

components/map/layers/cadastre.js, components/map/layers/numeros.js, components/map/layers/voies.js, components/map/map.js, components/map/style-selector.js, components/map/styles/index.js, components/map/styles/ortho.json, components/map/styles/plan-ign.json, components/map/styles/vector.json
Utilisation des fonds de cartes vecteur tuilés IGN. Suppression du style toponyme pour les valeurs suivantes : routier_borne, routier_numeor_lin et routier_donyme_lin
=> Ajout du fond de carte Plan IGN

components/breadcrumbs.js
Des utilisateurs ont remonté le besoin d’avoir la possibilité de retourner à la liste des Bases Adresses Locales.
Il est actuellement possible de cliquer sur le logo du site, mais cette utilisation n’est pas évidente pour tout le monde.
Cette PR propose donc d'ajouter une icône de maison dans le fil d’Ariane qui permet de retourner sur la page d’accueil du site.
Capture : 
Fix #474
=> Ajout d’une icône dans le fil d’Ariane

lib/utils/numero.js
Close #469 
La preview dynamique d'adresse permettait l'affichage du suffixe en majuscule.
Il est à présent automatiquement traité en minuscule.
=> Affichage des suffixes en minuscule dans la preview d'adresse

components/select-commune.js, lib/bal-api/index.js, pages/new/upload-form.js
resolves #380 
Cette PR permet de choisir une commune lors du téléversement d'un fichier csv.
- Ajout du composant `SelectCommune`
- Ajout d'un warning si un csv comporte plusieurs communes (remplace l'alerte danger)
- La route vers l'api pour l'upload devient `/bases-locales/${balId}/communes/${codeCommune}/upload`
Capture warning :
Capture vidéo :
https://user-images.githubusercontent.com/45098730/150108069-771b7d70-b2de-471d-b385-828fa3c0ea21.mp4
=> Permet de choisir une commune lors du téléversement d'un fichier csv

components/dashboard/counter.js, components/dashboard/published-bal-stats.js, lib/bal-api/index.js, lib/utils/numbers.js, pages/dashboard.js, pages/dashboard/departement.js
Remplace la PR #479
resolves #391
Ajout de 3 métriques concernant les bases adresses locales publiées
Capture
- Modification de la route pour l'appel à l'API : `/stats/bases-locales` devient `/stats`
- Ajout de `nbNumeros`
- Sur la page `departement`, les nouvelles métriques s'affichent uniquement s'il y a au moins une base adresse locale publiée
Capture
=> Ajout de métriques pour le tableau de bord

components/sub-header/bal-status/index.js
Cette PR retire le bouton "Publier" lorsqu'une BAL est en mode démonstration (`status === "demo"`)
Fix #497
=> Retire le bouton "Publier" en mode démonstration

components/dashboard/bal-creation-chart.js, components/dashboard/map.js, lib/bases-locales.js, lib/colors.js, pages/dashboard.js, pages/dashboard/departement.js
Actuellement la coloration des BAL sur la carte du dashboard se fait à l'aide d'un `geojson` des contours de toutes les communes de France sur lequel on vient appliquer une couche en fonction des données des BAL existantes.
Ce processus est lourd et dégrade les performances de l'outil.
Cette PR met en place les tuiles vectorielles pour les BAL. Cette fonctionnalité est apportée par [#309](#https://github.com/BaseAdresseNationale/mes-adresses-api/pull/309/files) et permet d'améliorer les performances globale du dashbord.
- Ajout des BAL `remplacées` indiqué par la couleur rouge
- Amélioration du code du composant carte du dashboard
=> Utilisation de tuiles vectorielle pour la cartographie du dashboard

components/dashboard/map.js
Une URL invalide a été laissé dans la PR #503. Celle-ci a été reçu un [hotfix](https://github.com/BaseAdresseNationale/mes-adresses/commit/a3f6e023470d8bcae16c93f45bfc27a2245bbcc3).
Cette PR vise à améliorer la gestion de l'URL de l'API BAL
=> Utilise l'URL de l'API BAL stockée dans l'environnement

components/base-locale-card/base-locale-card-content.js, components/base-locale-card/index.js, components/bases-locales-list/index.js, components/hidden-bal.js, components/user-bases-locales.js, contexts/local-storage.js, pages/index.js
resolves #487 
- Ajout du localstorage `hidden-bal` dans le context
- Ajout d'un bouton permettant de "cacher" la base adresse locale
- Ajout d'une alerte permettant de restaurer les bases adresses locales cachées
Capture vidéo :
https://user-images.githubusercontent.com/45098730/153556379-d15f4993-8117-4c32-992a-627e7b1aefc6.mp4
=> Permet d'enlever une base adresse locale de la liste sans la supprimer

pages/_app.js
Actuellement, les adresses mails des administrateurs sont tronquées lorsqu'elles sont trop longues.
Ce problème est dû à l’utilisation du Tooltip Evergreen dont la taille ne peux pas dépasser 240px.
Cette PR propose d’ajouter un style global à la racine du site pour modifier la classe qui empêche la `<div />` de s’agrandir.
J'ai ajouté un commentaire pour préciser le but de ce style global.
Avant : 
Après :
=> Corrige les adresses mails tronquées sur la page d’accueil

components/sub-header/bal-status/ban-sync/ban-history/revision.js
Fix #511 
Lorsqu'une BAL de l'historique de provient pas de Mes Adresses sa révisions ne possède pas de `extras.balId` ce qui provoque une erreur.
Cette correction rend `extras` optionnelle.
=> Correction de l'historique de publication

components/grouped-actions.js
Cette PR corrige le bug qui empêche la modale "Modifications Multiples" de se rouvrir après sa fermeture.
- Ajout de la propriété `onCloseComplete` sur la boite de dialogue Evergreen.
Fix #517
=> Corrige le bug de fermeture de la modale "Modifications Multiples"

pages/bal.js
La page `/bal` était auparavant utilisée pour afficher la liste des communes d'une Base Adresses Locale et permettre les actions de base d'édition, d'ajout et de suppression sur cette liste.
Cependant depuis l'intégration de l'API de dépôt #471, toutes les Bases Adresses Locales sont devenu mono-communale. Cette page est donc devenu obsolète. 
Cette PR propose d'ajouter une redirection vers la page `/commune` de la Base Adresse Locale. Cette redirection est temporaire en attendant le développement de #522 par exemple
.
=> Ajout d'une redirection sur la page /bal

components/bal/toponymes-list.js, components/bal/voies-list.js, components/table-row.js, components/table-row/index.js, components/table-row/table-row-actions.js, components/table-row/table-row-edit-shortcut.js, components/table-row/table-row-notifications.js, components/voie/numeros-list.js, pages/bal/commune.js
Le composant `<TableRow />` est un composant crucial et hautement utilisé dans l'outil. En effet, celui-ci s'occupe de la gestion des voies, toponymes et numéros dans leur liste respective. Il doit donc à la fois gérer les différents affichages (voie, toponyme, numéro) et leurs subtilités propres, permettre les différentes éditions possibles, mais dois également offrir un affichage sans aucune édition.
Il est devenu au fur et à mesure du temps un composant "fourre tout", d'une grande complexité et d'une rigidité ne permettant aucune évolution.
Cette PR propose de modifier le composant `<TableRow />` afin que celui-ci soit de nouveau réutilisable par les différents objet possible (voie, toponyme, numéro), que sa complexité soit éclatée dans différent composant dédié et qu'il prépare les …
=> Refonte du composant <TableRow />

components/map/numeros-markers.js
Lorsqu'une modification est apportée à une Base Adresse Locale **publiée**, le status "Synchronisation en cours" apparait.
Si le status apparaissait bien lors de la suppression depuis la liste des numéros, ce n'était pas le cas lors de la suppression depuis un marqueur de la carte.
Cette PR ajoute la fonction `refreshBALSync` dans le composant `numeros-markers` afin d’afficher le badge de synchronisation après une modification depuis la carte.
Fix #543
=> Corrige un problème d‘affichage du badge "synchronisation en cours"

components/new/upload-form.js
Un problème de comparaison entre code commune et clé interopérabilité a été découvert côté API lors de l'extraction des données [#323](https://github.com/BaseAdresseNationale/mes-adresses-api/pull/323).
Une comparaison semblable est également faite côté front afin d'extraire un code commune depuis la clé interopérabilité.
La `cle_interop` est passée en majuscule quand elle existe dans le but de concorder avec les codes communes utilisant des lettres (ex: 2B112)
**Mise à jour** :
Le code commune est extrait de `additionalValues.cle_interop.codeCommune` ou de `parsedValues.commune_insee`.
=> Fix csv import

components/map/numeros-markers.js, components/voie/numeros-list.js, pages/bal/voie.js
Lorsqu'un numéro est créé ou modifié, les données cartographiques `geojson` sont mises à jour uniquement si le numéro ne fais pas partie de la voie courante (ex : Changement de la voie du numéro). Cependant, le rechargement du `geojson` ne se faisant plus à chaque changement de voie comme précédemment pour des raisons de performances, les données n'étaient plus mises à jour.
Le nécessité de recharger les données cartographiques est désormais détectée, grâce à une variable `needGeojsonUpdate` extérieur au composant. Au lieu d'être effectuée à chaque modification et inutilement (la voie en cours étant filtrée pour afficher les marqueurs) la mise à jour des données ne se fera que si des changements ont été détectés et lorsqu'une nouvelle voie est chargée.
Fix #553
=> Correction du rafraîchissement des données cartographiques 

components/toponyme/add-numeros.js
Le système de sélection des numéros pour les toponymes souffrait de problèmes de clarté pour l'utilisateur.
La refonte complète de cette section permet à l'utilisateur de facilement sélectionner/désélectionner les numéros sans avoir besoin de consignes pour le guider.
- Tous les numéros sont sélectionnés par défaut
- En plus de la sélection individuelle, l'utilisateur a la possibilité de sélectionner / désélectionner l'entièreté des numéros
- La quantité totale de numéros sélectionnés s'affichent à droite du bouton
=> Amélioration du système de sélection de numéros pour les toponymes

lib/bal-api/index.js
Le message d'erreur afficher lorsqu'une tentative de publication échoue ne reste affiché que 5 secondes (valeur par défaut). Or ce message pouvant s'afficher lorsqu'une BAL n'est pas valide, il est important que les utilisateurs aient le temps de voir et de lire la notification les invitants à contacter le support.
Cette PR augmente à 30 secondes le temps d'affichage de la notification.
=> Add 30s duration on error publication toaster

components/new/create-form.js
Certains utilisateurs se plaignent de ne pas trouver leur commune dans le formulaire de recherche au moment de la création de leur Base Adresse Locale.
- Afficher tous les résultats en provenance de l’API : Cette solution demanderait le téléchargement d’un grand nombre de données dans l’application. Surtout que l’autocomplétion commence les appels à l’API dès les premiers caractères entrés dans la recherche.
- Modifier l’API : Cette solution nous obligerait à modifier un outil qui fonctionne très bien, avec le risque de ne plus afficher les résultats voulus dans ses autres utilisations.
Nous avons donc décidé d’ajouter simplement un message invitant l’utilisateur à entrer, en plus du nom de la commune, le numéro du département afin de pousser l’API à renvoyer la commune recherchée.
Avant …
=> Ajoute un message informatif pour la recherche de commune à la création d’une BAL

package.json, yarn.lock
Mise à jour de la dépendance `@etalab/bal` de la `v2.3.3` à la `v2.4.0`.
[Release v2.4.0](https://github.com/BaseAdresseNationale/bal/releases/tag/v2.4.0)
=> Mise à jour @etalab/bal en v2.4.0

components/bal/numero-editor.js
Cette PR corrige le bug #576 qui envoyait "Choisir un toponyme" lorsque l'utilisateur sélectionnait ce champ.
- Modification de la condition
- Suppression de conditions inutiles
Fix #576
=> Corrige la modification du toponyme d'un numéro

components/bal/numero-editor.js
resolve #575 
- Ajout de `reloadVoies` dans le composant `NumeroEditor` lors de l'envoi du formulaire
=> Actualise la liste des voies après la création d'une adresse

components/habilitation-process/index.js, components/sub-header/bal-status/index.js, components/sub-header/index.js, contexts/bal-data.js, hooks/habilitation.js
Il est actuellement impossible pour une commune de renouveler son habilitation afin de poursuivre ses publications dans la BAN.
Cette PR améliore la détection des habilitations invalides et affiche une notification avertissant l'utilisateur qu'il est nécessaire de la renouveler.
Pour renouveler l'habilitation, il suffit à l'utilisateur de cliquer sur "Publier" et de recommencer le processus d'habilitation. 
Un nouveau hook `useHabilitation` permet de mieux gérer l'habilitation d'une BAL et de propager son état de validité.
=> Correction du renouvellement d’habilitation

components/bal/address-editor.js, components/form.js
Le formulaire d'édition d'adresse ne s'adapte pas correctement à la hauteur du menu latéral. Deux problèmes d'affichage surviennent à cause de cela :
-  le formulaire de toponyme ne prend pas toute la hauteur du menu
- la prévisualisation de l'adresse sur le formulaire de numéro passe par-dessus le formulaire au moment du défilement.
**Exemple :**
https://user-images.githubusercontent.com/7040549/170995321-ebab9d21-70ab-4d69-b2fc-4e23ec834f9a.mov
- Correction de l'affichage des formulaires sur toute la hauteur du menu
- Ajoute de la prévisualisation de l'adresse sur la création d'un numéro
=> Correction de l’affichage de l'éditeur d’adresse

components/bal/position-editor.js
La fonction `addMarker` est appelé à chaque fois que le `viewport` est mis à jour, ce qui entraine de réinitialisation de marqueur sur la carte.
Cette réinitialisation est due au `useEffect` ayant lieu au montage du composant `PositionEditor` qui vient créer un marqueur par défaut (au centre de la carte avec une position "entrée") si aucune valeur n'est renseignée. Cependant, ce `useEffect` utilise `addMarker` dans ses `hooks`, or cette méthode se base sur le `viewport` de la carte. Ce dernier étant actualisé à chaque zoom/dézoome, le `useEffect` est alors appelé plusieurs fois et remplace le marqueur existant par un nouveau par défaut.
Cette PR retire `addMarker` et `handleAddMarker` des `hooks` du `useEffect` afin de ne plus être recalculé à chaque changement du viewport.
Fix #593
=> Correction de la réinitialisation du marqueur au changement de la fenêtre de visualisation de la carte

components/bal/address-editor.js, components/bal/numero-editor.js, components/bal/position-editor.js, components/bal/toponyme-editor.js, components/bal/toponymes-list.js, components/disabled-form-input.js, components/map/cadastre-control.js, components/map/map.js, components/map/style-selector.js, layouts/editor.js, lib/bal-api/index.js, pages/_app.js, pages/bal/commune.js, pages/bal/toponyme.js, pages/bal/voie.js
Actuellement, lorsque le cadastre n’est pas disponible pour une commune, rien dans l'affichage ne permet de le savoir.
Cette PR propose donc de masquer l’éditeur de parcelle cadastrale et de le remplacer par un message informant l’utilisateur de l’absence de cadastre pour la commune actuellement éditée.
Modifications effectuées : 
- Ajout de la propriété `hasCadastre` en provenance de l’API, permettant de savoir si le cadastre de la commune est disponible
- Ajout d’un composant `disabledInputForm` afin d’afficher un message lorsque le cadastre est indisponible
- Ajout d’une condition sur le bouton de la carte afin de le griser lorsque le cadastre est indisponible
- Correction des alertes en rapport avec le label de composants Evergreen
---
---
_Pour tester cette PR, vous pouvez utiliser …
=> Masque l’éditeur de parcelle lorsque le cadastre n’est pas disponible

components/map/controls/style-control.js, components/map/map.js
Certains territoires, comme les COM notamment, ne disposent pas de tous les fonds de carte que propose Mes Adresses (OpenMapTiles, Orthophoto, Plan IGN vecteur).
Cette PR propose de ne plus afficher les fonds de carte qui ne sont pas disponibles sur le territoire choisi en se basant sur les nouvelles propriétés `hasOrtho`, `hasOpenMapTiles` et `hasPlanIGN` .
Fix #590 
-----------
⚠️ Cette PR ne peut pas être merge avant https://github.com/BaseAdresseNationale/mes-adresses-api/pull/334
=> Désactive les fonds de carte indisponible sur le territoire

components/base-locale-card/index.js, components/commune-search/commune-search.js, components/new/demo-form.js
Les Collectivités d’Outre-Mer ne sont pour le moment gérer sur Mes Adresses pour différentes raisons techniques (voir BaseAdresseNationale/ban-bal/issues/4 et #531).
Un filtre est actuellement utilisé pour retirer les Collectivités d’Outre-Mer des territoires suggérés pour la création d’une Base Adresse Locale sur la page `/new`.
- Suppression du filtre des résultats sans code département (COM)
- Augmentation de la limite des résultats de `7` à `20`
- Seuls les résultats ayant un `_score` supérieur à `0.1` sont affichés
- Suppression de la props `exclude` inutilisée
- Ajout d'un `hint` et d'un `placeholder` sur le champ de création d'un BAL de démo
-----------
Les problèmes techniques étant en cours de résolution, cette PR propose de retirer le filtre afin que les Collectivités …
=> Suppression du filtre des Collectivités d’Outre-Mer au formulaire de création

components/map/map.js
Les espaces entre les boutons de contrôles de zoom et les actions telles qu'afficher/masquer les détails/toponymes et "Créer une adresse" n'étaient pas très harmonieux.
Cette PR tend à réarranger ces espaces afin de mieux séparer et regrouper les différentes actions.
=> Amélioration des espaces sur les contrôleurs de la carte

pages/dashboard.js
- `communeCount` retournait le nombre de commune sans prendre en compte leur caractère unique
resolves #624
=> Corrige le calcul du nombre de communes uniques dans le dashboard

package.json, yarn.lock
Mise à jour de @ban-team/validateur-bal de la version `2.7.1` à `2.8.0`.
Voir les détails de cette version 
https://github.com/BaseAdresseNationale/validateur-bal/releases/tag/v2.8.0
=> Mise à jour de @ban-team/validateur-bal

components/bal/language-preview.js, components/table-row/table-row-edit-shortcut.js
Lorsque qu'une adresse a plusieurs langues régionales, une simple liste à puces était affichée.
Pour apporter du contexte et permettre à l'utilisateur de savoir quelle est la langue régionale qu'il est en train de lire, les puces de la liste disparaissent au profit de l'affichage du drapeau correspondant.
=> Afficher les drapeaux de toutes les langues régionales dispo

components/bal/voie-editor.js, components/map/draw.js, components/voie/voie-heading.js, contexts/draw.js
Un utilisateur nous a remonté qu'il était devenu impossible d'éditer le tracé des voies.
En réalité l'édition était bien prise en compte, mais ce sont les données apportées au fond de carte qui n'était pas mise à jour.
Cette PR apporte les corrections et évolutions suivantes : 
- Corrige le rafraichissement des tracés de voies
- Corrige l'édition d'une voie en la sélectionnant depuis la carte
- Corrige l'édition du tracé en choisissant l'édition depuis le menu "..."
- Amélioration du nombre de rendus du composant de dessin (`ReactMapGLDraw`)
- Simplification du code du contexte `Draw` grâce à `BalDataContext.voie`
=> Correction du rechargement des tracés de voie

components/bal/toponyme-editor.js, components/toponyme/toponyme-heading.js, pages/bal.js, pages/bal/toponyme.js
Cette PR corrige #644 
--------
Cette correction est un "quick fix", elle répond au problème immédiat, mais n'est pas une solution perenne. En effet, dans le cas de petit écran (inférieur à 500px de haut), il sera toujours impossible de sauvegarder.
UPDATE : solution pérenne trouvée, peu importe la taille minimum de l'écran.
=> Correction du défilement pour la création d'un toponyme

contexts/draw.js
Depuis la dernière modification #642, il s'est avéré que la création de voie métrique pouvait poser un problème. En effet, après avoir créé une première voie avec un tracé, la création d'une seconde obtenait le tracé de la première.
1. Créer une voie A
2. Ajouter un tracé à cette voie A
3. Créer une voie B
4. Cocher la case "Cette voie utilise la numérotation métrique"
Le tracé de la voie A devrait être copié sur la voie B.
=> Correction du tracé de nouvelles voies

components/assisted-text-field.js, components/langues-regionales-form/language-field.js
La condition permettant la gestion du focus passe par une ref dans le composant AssistedTextField. Mais si isFocus est à false, alors la ref reçoit un booléen et provoque un crash de l'application, car une ref ne peut pas recevoir un booléen.
Ce fix permet d'éviter cette erreur en retournant `null` si `isFocus` vaut `false`
Close  #634
=> Correction de la gestion du focus dans le composant <AssistedTextField/>

package.json, yarn.lock
Resolves #649 
Corrige la typo `créole-réunionais` => `créole-réunionnais`
=> Mise à jour de @ban-team/shared-data vers la version 1.0.1

components/accent-tool.js, components/assisted-text-field.js, components/bal/numero-editor.js, components/bal/numero-editor/numero-voie-selector.js, components/bal/toponyme-editor.js, components/bal/voie-editor.js, components/demo-warning.js, components/langues-regionales-form/language-field.js, components/new/create-form.js, components/new/demo-form.js, components/new/upload-form.js, hooks/caret-position.js, hooks/focus.js
Le système de gestion de focus était obsolète. Nous utilisions un custom hook pour gérer les `ref` et ainsi, le focus sur les inputs.
Cette PR remplace le système mis en place par custom hook `useFocus` et exploite le hook `useRef` proposé par React, plus adapté. 
La refonte de la gestion du focus permet aussi de corriger le souci de retour du curseur à la fin du champ et non à sa position lorsqu'un caractère spécial est rajouté par l'outil d'accents.
Close #647 #646
=> Amélioration du système de focus

components/habilitation-process/validate-authentication/code-validation.js
Il est actuellement impossible d'ouvrir le formulaire d'authentification par code. Ce problème survient à un oubli de migration de composant lors de #583 
Le composant `<Form />` est remplacé par `<FormContainer />`.
Fix #671
=> Correction de l'ouverture du formulaire d'authentification

components/map/map.js
Lorsque que l'on change de page, la prop `commune` provoque le déclenchement d'un `useEffect` destiné à restituer le fond de carte précédent dans le cas où celui-ci aurait été volontairement changé par l'outil (ex : tracer une voie).
Cette PR propose de mémoriser la propriété `commune.hasOrtho` afin de ne pas déclencher de manière intempestive ce `useEffect`.
Fix #674
=> Corrige la réinitialisation du fond de carte au changement de page

components/bal/numero-editor/select-parcelles.js
Lors du survol d’un badge de parcelle dans l’éditeur de numéro, l’agrandissement de la taille du badge créait un clignotement et/ou un décalage perturbant pour l’utilisateur.
Ce comportement n’est pas présent sous MacOs.
Cette Pr propose d’augmenter légèrement la taille de la police de caractère afin d’éviter le clignotement.
Fix #661
=> Corrige le problème d’affichage des parcelles dans l’éditeur de numéro

components/sub-header/index.js, lib/bal-api/index.js
L'API renvoi désormais une erreur lorsqu'un BAL tente d'être publiée sans adresse.
Cette PR récupère correctement ce message et arrête le processus de publication si une erreur survient.
=> Empêcher la publication de BAL sans adresse

components/map/controls/control.js, components/map/map.js, package.json, pages/_app.js, yarn.lock
Celle PR remplace `mapbox-gl` par `maplibre-gl`, sa reprise open source.
- `maplibre-gl` est utilisé comme bibliothèque par `react-map-gl` à la place de `mapbox-gl`
- Les classes CSS `mapboxgl` sont remplacées par `maplibregl`
- `react-map-gl` a été mis à jour en `v5.3.19` (à partir de la v6.0.0`react-map-gl` utilise la `v2.0` non open source de `mapbox-gl`)
- Mise à jour de `react-map-gl` `v5.3.17` -> `v5.3.19`
- Mise à jour de `react-map-gl-draw` `v0.21.1` -> `v1.0.3`
Le package.json indique `npm:empty-npm-package@1.0.0` comme version de mapbox-gl. Cela a pour effet de rendre virtuelle la présence de `mapbox-gl` pour les dépences paires (cf Documentation [react-map-gl](https://visgl.github.io/react-map-gl/docs/get-started/get-started#using-with-a-mapbox-gl-fork)).
⚠️ Un ticket est …
=> Remplace mapbox-gl par map-libre-gl

components/base-locale-card/index.js
Sur la page` /dashboard`, lorsque l’on ouvrait le panneau des BALs, le badge de statut "à jour" n’avait pas la même taille que les autres badges.
Cette PR ajoute une taille minimum aux badges afin qu'ils aient la même taille au moment du wrap, peu importe la longueur du contenu.
----------------------------
Close #681
=> Corriger le badge de statut "à jour" écrasé des BALs

.env.sample, components/bal-recovery/recover-bal-alert.js, components/header.js, components/help/help-tabs/base-locale.js, components/help/help-tabs/numeros.js, components/help/help-tabs/publication.js, components/help/help-tabs/toponymes.js, components/help/help-tabs/voies.js, components/help/video-container.js, components/welcome-message.js
Cette PR ajoute les tutoriels vidéos en provenance de [peertube.adresse.data.gouv.fr](peertube.adresse.data.gouv.fr)
- Dans la boite de dialogue d’accueil à la création d’une BAL
- Dans la boite de dialogue de récupération d’une BAL
- Dans chaque onglet de la partie "Besoin d’aide"
Ainsi qu’un lien vers le peertube dans le menu de navigation.
Le composant `VideoContainer` possède une fonction qui permet de transformer un lien de partage en vidéo intégrée.
Fix  #123 
Captures :
=> Ajout des vidéos tutoriels mes-adresses

components/map/draw.js, components/map/map.js
Cette pull-request modifie le comportement du panneau informatif qui couvre les contrôles de la carte et du panneau d’édition.
Le composant a été déplacé afin de pourvoir être mieux disposé au-dessus de la carte sans empêcher l’utilisation des boutons de contrôle.
https://user-images.githubusercontent.com/56537238/191232984-4e217c30-df31-451e-bd62-c436df6f65a6.mov
https://user-images.githubusercontent.com/56537238/191233045-f1692642-5d8a-4562-aef3-93d29687b1ab.mov
Fix #699
=> Empêche le panneau d’information de la carte de couvrir les contrôles

components/base-locale-card/index.js, components/commune-search/commune-search.js, components/new/create-form.js, components/new/upload-form.js, pages/new.js
Resolves #608 
Resolves #615
- Le champ Commune est déplacé vers le haut du formulaire
- Le champ Nom de la Base Adresse Locale est rempli à la sélection de la commune : Adresse de 'commune sélectionnée' 
[Capture vidéo 2022-09-06 16:28:50.webm](https://user-images.githubusercontent.com/45098730/188635513-b8291c09-7ea2-4641-8d61-e390f534596a.webm)
edit : *09/09*
- Amélioration du remplissage automatique 
- Focus automatique sur la barre de recherche
=> Remplissage automatique du champ BAL à la sélection de la commune

components/sub-header/index.js
Le support a remonté un problème concernant une commune qui ne pouvait plus publier sa BAL en conflit. En cliquant sur le bouton "Publier" rien ne se passe.
Après une rapide investigation, il s'avère que ce problème concerne les BAL avec pour statut `replaced` dont l'habilitation a expirée.
Le statut `replaced` a été ajouté aux statuts acceptés pour demander une nouvelle habilitation.
1. Créer une BAL
2. Publier la BAL
3. Rendre obsolète son habilitation
4. Passer son status à `replaced`
=> Correction du renouvellement de l'habitation pour les BAL en conflit

components/map/hooks/bounds.js, components/map/map.js, contexts/map.js
Depuis l'ajout du recentrage de la caméra sur les numéros et toponymes multi-positions, le recentrage de la caméra se faisait de manière automatique sur l'élément de contexte restant. Dans le cas de l'édition de différents numéros d'une voie, l'utilisateur se retrouvé à être "dézoomé" au niveau de la voie après chaque édition. 
Ce comportement dégrade fortement le confort d'édition, notamment dans le cas de longue voie.
Le centrage de la caméra est dorénavant déclenché par le changement de contexte, comme la sélection d'une voie, le retour à la commune ou l'édition d'un numéro/toponyme à plusieurs positions. Ce de fait, l'utilisateur obtient une mise au point à la sélection du contexte et peut ensuite gérer lui-même sa caméra sans être recentré de force.
fix #708
=> Corrige le recentrage intempestif de la caméra

components/map/hooks/bounds.js
Ouvrir voie sans numéro provoque une erreur, car il n'est pas possible de calculer une bbox.
Renvoi les contours de la commune pour créer la bbox quand une voie n'a pas de numéro.
=> Corrige l'édition d'une voie sans numéro

components/grouped-actions.js
Lorsque plusieurs numéros sont édités et qu'ils ont différents toponymes, la sauvegarde entrainera nécessaire une suppression de tous les toponymes.
Cette suppression vient du fait que le champ `toponyme` est toujours attribué aux changements demandés alors que ce champ est `null` lorsque plusieurs toponymes sont présents.
Le champ `toponymes` n'est attribué aux changements que si un unique toponyme est détecté pour les numéros sélectionnés.
=> Correction de l'écrasement des toponymes dans l'édition multiple

components/mass-deletion-dialog.js, components/sub-header/index.js
Cette PR modifie le schéma de publication d’une Base Adresse Locale.
Précédemment, l’utilisateur devait cliquer deux fois sur le bouton "publier" pour voir apparaître la boite de dialogue proposant l’habilitation.
La demande d’habilitation s’affiche maintenant directement au moment de cliquer sur le bouton "publier".
=> Affiche la popup d’habilitation au clic sur le bouton "publier"

components/accent-tool.js
Ajout des caractères suivant (et leurs majuscules)  : 
- `ì` (`Ì`)
- `ò` (`Ò`)
La taille de la police a également était agrandi afin de mieux voir la différence entre certains accents.
=> Nouvel ajout de caractères dans l'outil d'aide à la saisi des noms de voie

components/bases-locales-list/index.js, components/bases-locales-list/public-bases-locales-list.js, components/new/create-form.js, components/new/upload-form.js, lib/bal-api/index.js, pages/all.js, pages/dashboard.js
Cette PR utilise l'évolution apportée par BaseAdresseNationale/mes-adresses-api/pull/365 afin de mettre en place une pagination sur la page `/all` et améliorer les performances de celle-ci.
- La méthode `listBasesLocales` a été renommé `getBasesLocales`
- La méthode `searchBAL` a été renommé `searchBasesLocale`
- La méthode `searchBasesLocale` demande `deleted: 0` par défaut en query afin de filtrer les bases locales supprimées.
- La barre permet de rechercher par code commune et non plus par nom
----------
⚠️ Cette PR nécessite les évolutions apportées par BaseAdresseNationale/mes-adresses-api/pull/365
=> Mise en place d'une pagination sur la page /all

components/toponyme/toponyme-heading.js, components/voie/voie-heading.js, pages/bal/toponyme.js
Cette PR est un quickfix qui a pour objectif de résoudre #745.
- S'assure que le `token` est bien présent au clique sur le nom d'une voie ou d'un toponyme.
- Cache le bouton "Ajouter des numéros" aux toponymes lorsque le `token` n'est pas présent
Fix #745
=> Correction de l'ouverture des formulaires d'édition en mode consultation

package.json, yarn.lock
Mise à jour de `@ban-team/validateur-bal` en version `2.13.0` pour la mise à jour du COG 2023.
=> Mise à jour du COG 2023

components/table-row/table-row-notifications.js
Les commentaire des numéro (ou il peut y avoir de l'information privé) peuvent être vu seulement dans les liste des voies et des toponyme sans avoir le token le la BAL.
On check le token pour afficher les commentaires
Fix https://github.com/BaseAdresseNationale/mes-adresses/issues/753
=> Amélioration: Ajouter un check du token pour lire les commentaires

components/habilitation-process/index.js, components/sub-header/bal-status/ban-sync/sync-button.js, components/sub-header/index.js
Lors d'un conflit de BAL, on peut appuyer frénétiquement sur le bouton `Forcer la mise à jour`, ce qui lance plein de requêtes `/bases-locales/${balId}/sync/exec`concurentes.
Bloquer le bouton  `Forcer la mise à jour` pendant qu'une requête est en cour
=> Disbabled button force sync lorsque qu'une requête est en cour

components/bal/voies-list.js, components/convert-voie-warning.js, components/table-row/table-row-actions.js, lib/bal-api/index.js, pages/bal.js
Il arrive fréquemment que des communes créent des voies sans adresse qui, dans la grande majorité des cas, devraient être des toponymes. De plus les voies sans adresse ne remonte pas la BAN.
Permettre de "convertir" une voie sans adresse en toponyme grâce à une action disponible dans le menu de la voie.
Cette opération devra être effectuée par une route dédiée sur mes-adresses-api.
- Ajout de la props `extra: {callback, icon, text}`sur la fonction composant `TableRowActions` qui permet de passer une action supplémentaire.
- Ajout de la fonction `convertVoieToToponyme` dans `bal-api/index.js` qui requète la nouvelle route de api-bal `/voies/${idVoie}/convert-to-toponyme`.
- Ajout d'un useCallback `onConvert` dans la fonction composant `BaseLocal` qui appelle la fonction …
=> Nouvelle fonctionalité: convertir voie en toponyme

package.json, yarn.lock
Première PR vers la mise à jour de toutes les dépendances de Mes Adresses afin de rattraper tout le retard accumulé et passer sous Node 18.
- `@babel/runtime` : `7.17.9` -> `7.21.0`
- `@babel/core` :  `7.17.10` -> `7.21.3`
- `@babel/eslint-parser` : `7.17.0` -> `7.21.3`
- `immutable` : `4.0.0`-> `4.3.0`
=> Mise à jour mineures de certaine dépendances

components/convert-voie-warning.js, pages/bal.js
Lors de la conversion d'une voie en toponyme, comme la requète convertToToponyme peut être long, on pouvait cliqué sur `confirmé` et ensuite fermer la popup en pensant que rien ne c'était passé.
Ajout d'un loader sur le bouton `confirmé` et disabled des bouton `cancel` et `close` pendant la requète
=> Fixé les button de la popup pendant la requète convertToToponyme

.env.sample, hooks/matomo-tracker.js, pages/_app.js
Afin de mesurer l'utilisation du site mes-adresses, nous ajoutons le tracker Matomo
- Création d'un hook "useMatomoTracker" pour gérer le tracking de l'application (track la page sur laquelle l'utilisateur arrive et toutes les pages qu'il visite)
- La page contenant le token d'une BAL dans l'URL n'est pas trackée
- Ajouter NEXT_PUBLIC_MATOMO_SITE_ID et NEXT_PUBLIC_MATOMO_TRACKER_URL dans le .env et passer "trackingEnabled" à true
=> Ajoute le tracking Matomo

.env.sample, lib/ban-api-depot.js
Les appels vers l'API dépôt sont aujourd'hui redirigés de https://plateforme.adresse.data.gouv.fr/api-depot vers https://plateforme-bal.adresse.data.gouv.fr/api-depot.
Cette PR met à jour la variable d'environnement et l'URL de fallback pour pointer directement vers la nouvelle URL https://plateforme-bal.adresse.data.gouv.fr/api-depot
=> Mise à jour des URL vers l'API dépôt

components/sub-header/index.js, contexts/bal-data.js, hooks/habilitation.js, hooks/publish-process.js
Dans le cadre du chantier sur le panneau d'information, nous avons besoin mutualiser les fonctions de publication d'une BAL entre plusieurs composants.
Il s'agit déplacer les fonctions qui gèrent la publication d'une BAL dans le hook usePublishProcess
S'assurer qu'il n'y ait pas de régression sur les fonctionnalités actuelles
=> Déplace les fonctions de publication d'une BAL dans un hook dédié

components/map/controls/image-control.js, components/map/controls/layer-show-hide-zoom-control.js, components/map/controls/map-layer-control.js, components/map/layers/tiles.js, components/map/map.js, package.json, yarn.lock
https://github.com/BaseAdresseNationale/mes-adresses/issues/243
=> Map to image

pages/dashboard.js, pages/dashboard/departement.js
Comme la route /couverture-tiles/:z/:x/:y.pbf contient toutes les geojson de toute les communes de france et qu'il y a plusieurs instance de mes-adresses-api en prod, cela fait exploser la RAM
Exemple après connection a la page https://mes-adresses.data.gouv.fr//dashboard
Désactivation de la route /couverture-tiles/:z/:x/:y.pbf avant fix final
=> disbaled page dashboard

components/sub-header/bal-status/publication.js
Pour une BAL en conflit j'ai cette erreur dans la console
Ajouter `replaced` dans les valeur probable de status dans les propTypes du component Publication
=> correct error console props status component publication

components/map/editable-marker.js
- lorsque l'on déplace un point sur une voie métrique le numéro ne s'update plus en live mais dès que le clic la souris est released
=> fix bug on drag marker numero

components/grouped-actions.js
- lorsque l'on réassigne tous les numéros d'une voie ils disparaissent sur le niveau de zoom séléctionné + d'autres zoom > problème plutôt lié au refresh
=> fix multi numero update voie

components/map/editable-marker.js
Lors de l'édition de la deuxième position d'un numéro, les coordonées de cette dernière n'était modifiable sur la map.
=> Correct bug editable marker not working

components/sub-header/bal-status/index.js
Le status `en attente d'habilitation` est embrouillant pour les communes, elles ne savent pas quoi faire
Ajout d'un bouton `Habiliter la BAL` qui ouvre la popup d'habilitation lorsque le status est `en attente d'habilitation` a coté du status
=> Add button habilitation when status is waiting-habilitation

components/map/styles/ortho.json, components/map/styles/plan-ign.json
L’infrastructure actuelle du Géoportail ferme le 15 mars 2024. Il faut migrer sur Géoplateforme
https://geoservices.ign.fr/bascule-vers-la-geoplateforme
=> migration: map url geoportail to geoplaforme

components/new/upload-form.tsx
Le bug est reproductible seulement avec Windows + Firefox.
Si Excel est installé sur le poste, le type du fichier devient application/vnd.ms-excel plutôt que text/csv ce qui fait que Nest.js rejette l'upload.
=> fix: incorrect content type on bal upload (windows and firefox)

components/habilitation-process/index.tsx, contexts/bal-data.tsx, lib/statuses.ts
- Comme on active le mode `pause` lorsque l'habilitation est erroné, il faut que le èn attente d'habilitation` overwrite le status `pause`
- Lorsque que l'on valide une habilitation on reload la BAL pour vérifié si le `isPaused` a changé
=> feat: mode pause

components/map/editable-marker.tsx, lib/utils/numero.ts
- A la création, le numero change toujours lorsque l'on bouge une position supplémentaire sur les voie métrique
- A la création, le numero est marqué `undefined` sur la map
=> fix: bug multi markers in metrique voie

components/bal/certification-infos.tsx, contexts/bal-data.tsx, lib/openapi/services/BasesLocalesService.ts
Lorsque l'on certifie toutes les adresses, si c'est une erreurs, il n'y a plus cas recréer la BAL
Nouveau bouton dans l'accordion `en savoir plus sur la certification` pour décertifier toute la BAL
=> feat: decertifie all numeros

components/bal/certification-infos.tsx, components/bal/voies-list.tsx, contexts/bal-data.tsx, lib/openapi/services/BasesLocalesService.ts
Il est compliqué pour les communes de trouver les adresses certifiées quand il n'en reste que quelque unes
Ajout d'un bouton filtre directement sur la liste des voies
=> filter: voie uncertifie

components/base-locale-card/index.tsx, contexts/token.tsx
Lorsque l'on est sur /bal/... qui est `en cours de mise a jour` et que l'on revient sur l'accueil
Et qu'on reclique sur la bal en question
Celle ci est maintenant `en attente d'habilitation`
Lorsque l'on retourne sur l'accueil, nous forcons le OpenApi.TOKEN (pour savoir si les bal sont habilité), le token est alors désynchro entre celui de OpenApi.TOKEN et du TokenContext.
Comme le Token du TokenContext n'a pas changé, le reloadHabilitation ce lance avec un OpenApi.TOKEN erroné, ce qui nous donne un une 403.
On set le token de OpenApi.TOKEN et du TokenContext a null quand il n'y a pas de balId (dans la requète)
=> fix: bug token when change bal

components/base-locale-card/base-locale-card-content.tsx, pages/bal/[balId]/index.tsx
Les communes ne comprennent pas tjs qu'il faut cliquer sur `gérer les adresses` lorsque la BAL est `en attente d'habilitation`
- Ajout d'un bouton `habiliter la BAL`sur la card qui redirige sur la page /bal
- Sur la page /bal, ouvre automatiquement la popup d'habilitation si le status est en `waiting habilitation`
=> feat: button habilitation on bal card

layouts/editor.tsx
On peut accéder a une BAL supprimé via le lien d'admin
Ajouter query params dans la requète GET /bases_locales pour préciser que la BALs doit exister
=> fix: hide bal deleted with link /bal

components/user-bases-locales.tsx
Un tri pour que les Bals soit par ordre de date de dernière mise a jour sur la page d'accueille
=> fix: list bals by updated_at

components/bal/voies-list.tsx, components/comments-content.tsx, lib/openapi/models/ExtendedBaseLocaleDTO.ts, lib/openapi/models/ExtendedVoieDTO.ts, lib/openapi/models/Voie.ts
- Changement des DTO ExtendedVoieDTO et Voie
=> Feat: change extended voie

contexts/bal-data.tsx, pages/bal/[balId]/voies/[idVoie].tsx
Corrige deux bugs :
- Quand on est sur un toponyme et on clique sur une voie via la map, les numéros du toponyme sont gardés pour la voie.
https://www.loom.com/share/b5d22541251244b58159c4a4e6cbc854
- Le champ commentaire apparait vide pour les numéros
https://www.loom.com/share/f0d9199dd93a478ea27c9f3ef469a300
=> fix: bug commentaire voie

components/bal/commune-editor.tsx, components/bal/toponyme-editor.tsx, components/bal/voie-editor.tsx, components/langues-regionales-form/index.tsx, components/langues-regionales-form/language-field.tsx, components/sidebar/header.tsx, lib/openapi-api-bal/models/BaseLocale.ts, lib/openapi-api-bal/models/ExtendedBaseLocaleDTO.ts, lib/openapi-api-bal/models/UpdateBaseLocaleDTO.ts, pages/bal/[balId]/index.tsx
Pourvoir modifier le nom alternatif de la commune
Visualisation du nom régionale de la commune
Auto selection de la langue régionale pour les voies et toponymes lorsque celle de la commune est remplit
=> feat: add nomAlt to commune 

components/bal/position-editor.tsx
Ajouter un message pour l'édition des positions sur la carte
=> feat: add alert on edition position

components/new/create-form.tsx, lib/openapi-api-bal/services/BasesLocalesService.ts
- Lorsque le populate recoit une 504 TIMEOUT, on setInterval la route /is_populating jusqu'a ce que la BAL soit populate
=> fix: waiting when populate return 504

components/bal/toponymes-list.tsx, components/bal/voies-list.tsx
On a eu quelque message au support de commune qui ne comprenait pas quand elles étaient en mode consultation et qui étaient perdus
Ajouter la card pour `Récupérer les accès`sur les onglets voies et toponymes
=> feat: add card recover access in onglet voies and toponymes

components/map/hooks/bounds.ts, layouts/editor.tsx, lib/openapi-api-bal/models/ExtendedBaseLocaleDTO.ts, lib/openapi-api-bal/models/ExtendedVoieDTO.ts, lib/openapi-api-bal/models/Voie.ts, pages/bal/[balId]/signalements/index.tsx, types/commune.ts
Lorsque l'api-geo ne répond pas, cela fait planter mes-adresses car on ne récupère pas le contour dans la fonction `getBaseEditorProps` de `editor.tsx`.
De même on ne peut pas aller sur les BALs des ancienne commune
Catch si l'api-geo ne répond pas et calculer la `bbox` par rapport au bbox des voies de la BAL
=> feat: delete dependance api-geo to contour commune

components/bal/position-editor.tsx, components/bal/toponyme-editor.tsx
Le toponymes sans position ne remonte pas dans la BAN, on ne veut donc plus de toponyme sans position
- Ajout automatique d'une position a l'ouverture d'un toponyme sans position
- Impossible de supprimer la position du toponyme si il y en a qu'une
=> feat: toponyme must have position
